### ISSUE TITLE
Tarea del Modulo 1.1

### ISSUE THREAD

**Issue by Alexander-Cervantes** [SistemasTecTlaxiaco/CursoGitHubAlexander#1]
Para aprender a utilizar herramientas nuevas que desarrollen la capacidad de los estudiantes y profesores del trabajo colaborativo

**Comment by Alexander-Cervantes** [comment]
¿Por que querías usar GitHub en el salón de clases?

**Comment by josealfredo79** [comment]
Bien hecho y revisado la tarea 1.1
